name: PHP Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Run PHP lint
      run: find . -type f -name "*.php" -exec php -l {} \;

    - name: Run PHPUnit tests
      run: |
        if [ -f ./vendor/bin/phpunit ]; then ./vendor/bin/phpunit --configuration phpunit.xml; fi

    - name: WordPress Coding Standards
      uses: wearerequired/lint-action@v1
      with:
        phpcs: true
        paths: |
          ./includes
          ./admin-notification-manager.php
      env:
        PHPCS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
